name: movie_diary
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  google_sign_in: ^6.3.0
  url_launcher: ^6.3.1
  loading_animation_widget: ^1.3.0
  typicons_flutter: ^0.5.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/App_Icon.png
    - assets/Wallpaper.png
    - assets/Profile.png
    - assets/TMDB.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600

flutter_icons:
  android: true
  ios: true
  image_path: "assets/App_Icon.png"